### ISSUE TITLE
Change WASI object to Wasi interface to ease testability

### ISSUE THREAD

**Issue by andylamax** [sdeleuze/kowasm#10]
Can we please make WASI an interface so that we may be able to inject Fake WASI runtimes during testing

**Comment by andylamax** [comment]
That was a very quick reaction. I trully appreciate

**Comment by skuzmich** [comment]
Btw, it is also possible to inject fake WASI in JS wrapper: https://github.com/sdeleuze/kowasm/blob/main/wasi/runner.mjs#L10
